project:
  type: website

website:
  title:  ğŸ”ï¸ Climate Chronicles -  Southeastern Utah's National Parks 
  navbar:
    background: primary
    tools:
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/isfarbaset/story-project
  sidebar:
    style: "floating"
    search: false
    contents:
      - section: "Temperature Tales ğŸŒ¡ï¸"
        contents:
          - index.qmd
      - section: "Blazing Trends ğŸ”¥"
        contents:
          - temp.qmd
      - section: "Soil Sizzle ğŸ‚"
        contents:
          - soil.qmd
      - section: "Evaporation Station ğŸŒ¤ï¸"
        contents:
          - evap.qmd
      - section: "Raindrops and Vapors ğŸŒ§ï¸"
        contents:
          - ppt.qmd
      - section: "It's A Wrap ğŸŒ¿"
        contents:
          - conclusion.qmd
    # contents:
    #   - index.qmd
    #   - pages/treecanopy/treecanopy.qmd
    #   - pages/trend/trend.qmd
    
format:
  html:
    theme: cosmo
    toc: true
